SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(TARGET_TRIPLET "arm-none-eabi-")

# Perform compiler test with the static library
SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

SET(CMAKE_C_COMPILER ${TARGET_TRIPLET}gcc)
SET(CMAKE_CXX_COMPILER ${TARGET_TRIPLET}g++)
SET(CMAKE_ASM_COMPILER ${TARGET_TRIPLET}gcc)
SET(CMAKE_LINKER ${TARGET_TRIPLET}gcc)
SET(CMAKE_SIZE_UTIL ${TARGET_TRIPLET}size)
SET(CMAKE_OBJCOPY ${TARGET_TRIPLET}objcopy)
SET(CMAKE_OBJDUMP ${TARGET_TRIPLET}objdump)
SET(CMAKE_NM_UTIL ${TARGET_TRIPLET}gcc-nm)
SET(CMAKE_AR ${TARGET_TRIPLET}gcc-ar)
SET(CMAKE_RANLIB ${TARGET_TRIPLET}gcc-ranlib)

SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Compiler and linker flags
SET(CMAKE_COMMON_FLAGS "${MCPU_FLAGS} ${VFP_FLAGS} -g3 -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-builtin -fno-common -Wall -Wshadow -Wdouble-promotion -Werror -Wno-unused-parameter")

SET(CMAKE_C_FLAGS_INIT "${CMAKE_COMMON_FLAGS}")
SET(CMAKE_CXX_FLAGS_INIT "${CMAKE_COMMON_FLAGS}")
SET(CMAKE_ASM_FLAGS_INIT "${CMAKE_COMMON_FLAGS}")
SET(CMAKE_EXE_LINKER_FLAGS_INIT "${LD_FLAGS} --specs=nano.specs -Wl,--gc-sections,-print-memory-usage")

SET(CMAKE_C_FLAGS_DEBUG_INIT "-O0")
SET(CMAKE_CXX_ASM_FLAGS_DEBUG_INIT "-O0")
SET(CMAKE_ASM_FLAGS_DEBUG_INIT "")
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "")

SET(CMAKE_C_FLAGS_RELEASE_INIT "-Os -flto")
SET(CMAKE_CXX_FLAGS_RELEASE_INIT "-Os -flto")
SET(CMAKE_ASM_FLAGS_RELEASE_INIT "")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "-flto")
